# Generated by Django 3.2.2 on 2021-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
    ]
